workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      vars:
        XCODE_PROJECT: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.example.crmApp"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "com.example.crmApp" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Get Flutter packages
        script: flutter pub get
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist=/tmp/exportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true

  macos-workflow:
    name: macOS Workflow
    environment:
      vars:
        XCODE_PROJECT: "macos/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.example.crmApp"
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Flutter build macos
        script: |
          flutter build macos --release
    artifacts:
      - build/macos/Build/Products/Release/*.app
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true

  android-workflow:
    name: Android Workflow
    environment:
      android_signing:
        - keystore_reference
      vars:
        PACKAGE_NAME: "com.example.crmApp"
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Flutter build apk
        script: flutter build apk --release
      - name: Flutter build appbundle
        script: flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      google_play:
        track: internal
        submit_as_draft: true 