name: Flutter CRM CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Build and Test Job (Android & Web)
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Analyze code
      run: flutter analyze --no-fatal-infos
      
    - name: Run tests
      run: flutter test
      
    - name: Build APK
      run: flutter build apk --release
      
    - name: Build Web
      run: flutter build web --release
      
    - name: Build iOS (Basic - no signing)
      run: flutter build ios --release --no-codesign
      
    - name: Build macOS
      run: flutter build macos --release
      
    - name: Build Windows
      run: flutter build windows --release
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk
        
    - name: Upload Web build artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: build/web/
        
    - name: Upload iOS build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: build/ios/iphoneos/
        
    - name: Upload macOS build artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: build/macos/Build/Products/Release/
        
    - name: Upload Windows build artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: build/windows/runner/Release/

  # Code Quality Job
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Run linter
      run: flutter analyze --no-fatal-infos
      
    - name: Check code formatting
      run: dart format --set-exit-if-changed .

  # Security Scan Job
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run security scan
      uses: github/codeql-action/init@v3
      with:
        languages: dart
        queries: security-extended,security-and-quality
        
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

  # Deploy to Supabase (if on main branch)
  deploy:
    needs: [build-and-test, code-quality, security-scan]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        
    - name: Build for production
      run: flutter build web --release
      
    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest
        
    - name: Deploy to Supabase
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      run: |
        echo "Deploying to Supabase..."
        
        # Check if secrets are available
        if [ -z "$SUPABASE_ACCESS_TOKEN" ]; then
          echo "❌ Error: SUPABASE_ACCESS_TOKEN not set."
          echo "Please add SUPABASE_ACCESS_TOKEN to your repository secrets:"
          echo "1. Go to: https://github.com/aaryesha17/AluminumFormworkCRM/settings/secrets/actions"
          echo "2. Click 'New repository secret'"
          echo "3. Name: SUPABASE_ACCESS_TOKEN"
          echo "4. Value: Your Supabase access token from https://supabase.com/dashboard/account/tokens"
          exit 1
        fi
        
        if [ -z "$SUPABASE_DB_PASSWORD" ]; then
          echo "❌ Error: SUPABASE_DB_PASSWORD not set."
          echo "Please add SUPABASE_DB_PASSWORD to your repository secrets:"
          echo "1. Go to: https://github.com/aaryesha17/AluminumFormworkCRM/settings/secrets/actions"
          echo "2. Click 'New repository secret'"
          echo "3. Name: SUPABASE_DB_PASSWORD"
          echo "4. Value: Your Supabase database password"
          exit 1
        fi
        
        echo "✅ Secrets are configured. Starting Supabase deployment..."
        
        # List available projects (for debugging)
        echo "Available Supabase projects:"
        supabase projects list || echo "Could not list projects - check access token"
        
        # Link to your Supabase project
        # Project: tobler-crm (vlapmwwroraolpgyfrtg)
        echo "Linking to Supabase project: tobler-crm..."
        supabase link --project-ref vlapmwwroraolpgyfrtg
        
        # Push database migrations
        echo "Pushing database migrations..."
        supabase db push
        
        # Deploy Edge Functions (if any)
        echo "Deploying Edge Functions..."
        supabase functions deploy
        
        # Deploy any custom configurations
        echo "Deploying configurations..."
        supabase config push
        
        echo "✅ Supabase deployment completed successfully!" 