name: Release Management

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build APK
      run: flutter build apk --release
      
    - name: Build Web
      run: flutter build web --release
      
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          build/app/outputs/flutter-apk/app-release.apk
          build/web/**/*
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Deploy to Supabase (Optional)
      if: github.ref == 'refs/tags/v*'
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      run: |
        echo "Deploying release to Supabase..."
        # Add your Supabase deployment commands for releases
        # For example:
        # supabase db push --db-url ${{ secrets.SUPABASE_DB_URL }}
        # supabase functions deploy
        echo "Release deployment completed!" 